#!/usr/bin/env python3
"""Deterministic extractor for the Mongoose TLS subtree.

Phase 22 Stage D U18. Consumes `kernel/net/mongoose.c` and emits
`user/libtls-mg/mongoose_tls_core.c` containing the TLS 1.3 slice plus
the minimum helpers it depends on (SHA-256, base64, X25519, AES-GCM/CTR,
ChaCha20-Poly1305, P-256 ECDSA via uecc, the builtin TLS state machine).

Mongoose's amalgamated source uses "#line 1 \"src/NAME.c\"" markers to
announce each original translation unit. We index those markers, slice out
the TLS-relevant ranges in source order, and append them to the output —
keeping the markers so compile errors cross-reference back to the upstream
line numbers cleanly.

The script is intentionally rule-based (no Python parsing) because the
extraction is mechanical and must be reproducible across Mongoose updates.

Usage: python3 extract.py [--src PATH] [--out PATH]
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

# Ordered list of the Mongoose files that contribute to TLS 1.3. Order
# matters: later files may reference symbols defined earlier.
TLS_SLICES = [
    "base64.c",       # Used by PEM decoding
    "sha1.c",         # For TLS 1.2 fallback (harmless for 1.3-only use)
    "sha256.c",       # HKDF + transcript hash
    "tls_aes128.c",   # AES-GCM record layer (TLS 1.3 AEAD)
    "tls_chacha20.c", # Alternative AEAD
    "tls_x25519.c",   # Ephemeral key exchange
    "tls_uecc.c",     # P-256 ECDSA for server cert verify
    "tls_builtin.c",  # The 1.3 protocol driver itself
]

# Files we don't want (alternative TLS backends, unrelated Mongoose bits).
SKIP_FILES = {
    "tls_dummy.c",
    "tls_mbed.c",
    "tls_openssl.c",
}

LINE_RE = re.compile(r'^#line 1 "src/([^"]+)"\s*$')


def index_sections(src_lines: list[str]) -> list[tuple[str, int]]:
    """Return [(filename, starting line 1-indexed), ...] for every #line block."""
    out: list[tuple[str, int]] = []
    for i, line in enumerate(src_lines, start=1):
        m = LINE_RE.match(line.rstrip('\n'))
        if m:
            out.append((m.group(1), i))
    return out


def extract_slice(src_lines: list[str], index: list[tuple[str, int]],
                  filename: str) -> list[str]:
    """Return the [start..end] lines for `filename`, inclusive of header."""
    for idx, (name, start) in enumerate(index):
        if name == filename:
            end = index[idx + 1][1] - 1 if idx + 1 < len(index) else len(src_lines)
            return src_lines[start - 1:end]
    raise KeyError(f"Mongoose section {filename!r} not found in amalgamation")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--src', default='vendor/mongoose.c',
                    help='Path to the amalgamated Mongoose source. Default points '
                         'to user/libtls-mg/vendor/mongoose.c (Phase 22 closeout '
                         'restored from git aed9c15:kernel/net/mongoose.c).')
    ap.add_argument('--out', default='mongoose_tls_core.c',
                    help='Destination for the extracted slice.')
    args = ap.parse_args()

    src_path = Path(args.src)
    if not src_path.exists():
        print(f"error: {src_path} does not exist", file=sys.stderr)
        return 2

    src_lines = src_path.read_text(encoding='utf-8', errors='replace').splitlines(True)
    index = index_sections(src_lines)

    sections: list[tuple[str, list[str]]] = []
    for fname in TLS_SLICES:
        try:
            lines = extract_slice(src_lines, index, fname)
        except KeyError as exc:
            print(f"warning: {exc}", file=sys.stderr)
            continue
        sections.append((fname, lines))

    # Prepend the core-shim ABI our shim expects. The shim exposes the
    # minimal mg_connection surface that the extracted code dereferences,
    # plus the weak hooks libtls_shim.c implements (_mgtls_drive_handshake,
    # _mgtls_encrypt_app, _mgtls_decrypt_app).
    preamble = [
        "/* AUTO-GENERATED by user/libtls-mg/extract.py. DO NOT EDIT BY HAND. */\n",
        "/* Source: kernel/net/mongoose.c (Mongoose TLS subtree). */\n",
        "\n",
        "#define MG_TLS MG_TLS_BUILTIN\n",
        "#include \"mongoose_tls_core.h\"\n",
        "\n",
    ]

    out_path = Path(args.out)
    with out_path.open('w', encoding='utf-8') as fp:
        fp.writelines(preamble)
        for fname, lines in sections:
            fp.write(f"\n/* --- {fname} --- */\n")
            fp.writelines(lines)

    print(f"wrote {out_path} ({sum(len(ls) for _, ls in sections)} lines)")

    # Emit the accompanying header so the core compiles cleanly against our
    # shim stubs. The header declares the mg_* types that the extracted code
    # references and wires up the hooks the shim expects.
    header_lines = [
        "/* AUTO-GENERATED by user/libtls-mg/extract.py. DO NOT EDIT. */\n",
        "#pragma once\n",
        "#include <stdint.h>\n",
        "#include <stddef.h>\n",
        "#include <string.h>\n",
        "#include <stdlib.h>\n",
        "\n",
        "#define MG_TLS_NONE     0\n",
        "#define MG_TLS_MBED     1\n",
        "#define MG_TLS_OPENSSL  2\n",
        "#define MG_TLS_BUILTIN  4\n",
        "#define MG_TLS_BUILTIN_AEAD_AES128_GCM   1\n",
        "#define MG_TLS_BUILTIN_AEAD_CHACHA20     2\n",
        "\n",
        "/* Minimal mg_* stand-ins for the extracted code. Full shim lives in */\n",
        "/* libtls_shim.c; the extracted TU sees this header only. */\n",
        "typedef struct mg_iobuf { uint8_t *buf; size_t len, size, align; } mg_iobuf_t;\n",
        "struct mg_connection;\n",
        "extern int mg_rand(void *, size_t);\n",
        "extern void mg_log(const char *fmt, ...);\n",
        "extern void mg_error(struct mg_connection *, const char *fmt, ...);\n",
    ]
    hdr_path = out_path.with_suffix('.h')
    with hdr_path.open('w', encoding='utf-8') as fp:
        fp.writelines(header_lines)
    print(f"wrote {hdr_path}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
