/* AUTO-GENERATED by user/libtls-mg/extract.py. DO NOT EDIT. */
#pragma once
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <stdlib.h>

#define MG_TLS_NONE     0
#define MG_TLS_MBED     1
#define MG_TLS_OPENSSL  2
#define MG_TLS_BUILTIN  4
#define MG_TLS_BUILTIN_AEAD_AES128_GCM   1
#define MG_TLS_BUILTIN_AEAD_CHACHA20     2

/* Minimal mg_* stand-ins for the extracted code. Full shim lives in */
/* libtls_shim.c; the extracted TU sees this header only. */
typedef struct mg_iobuf { uint8_t *buf; size_t len, size, align; } mg_iobuf_t;
struct mg_connection;
extern int mg_rand(void *, size_t);
extern void mg_log(const char *fmt, ...);
extern void mg_error(struct mg_connection *, const char *fmt, ...);
