// user/include/gcp_ops_generated.h
//
// GENERATED by scripts/gen_manifest.py from /etc/gcp.json. DO NOT EDIT.
// Userspace OP_* constants and GCP_TYPE_HASH_* macros for Phase 18.

#pragma once
#include <stdint.h>

// Opcodes. Values must match kernel/io/stream.h (enforced at runtime
// when the shared sqe_t is validated against the kernel op_schema).
#define OP_READ_VMO   1u
#define OP_WRITE_VMO  2u
#define OP_SENDMSG    3u
#define OP_OPEN       4u
#define OP_STAT       5u
#define OP_FSYNC      6u
#define OP_CLOSE      7u

// Type-hash macros. FNV-1a 64-bit of the manifest type string.
#define GCP_TYPE_HASH_IO_V1                      0x731C934A2C6A037BULL
#define GCP_TYPE_HASH_IO_COMPLETION_V1           0xD4D893156B1C7693ULL
#define GCP_TYPE_HASH_NOTIFY_V1                  0x8CE1B2F34A88A610ULL
#define GCP_TYPE_HASH_PIPE_BYTES_V1              0xDDE77B853FE8322CULL
#define GCP_TYPE_HASH_FAULT_V1                   0x94373FD4B7C1ED43ULL
#define GCP_TYPE_HASH_SHUTDOWN_V1                0xB9BB0AACFACA5045ULL
#define GCP_TYPE_HASH_AUDIT_V1                   0x0A8D84AA8BE2E342ULL
#define GCP_TYPE_HASH_TEST_V1                    0xACC7E516EE71F1B3ULL
#define GCP_TYPE_HASH_NET_FRAME_V1               0x907BAAAD52A368B3ULL
#define GCP_TYPE_HASH_NET_SERVICE_V1             0x19111BEED5E4736DULL
#define GCP_TYPE_HASH_NET_SOCKET_V1              0xA48A3EFE1139CA79ULL
#define GCP_TYPE_HASH_NET_ACCEPT_V1              0xF120F11A7BA1870EULL
#define GCP_TYPE_HASH_BLK_SERVICE_V1             0xFB1E9BA25588A4A9ULL
#define GCP_TYPE_HASH_BLK_LIST_V1                0x671270DA03116FF6ULL

// SQE/CQE flag mirrors — values match kernel/io/stream.h.
#define SQE_FLAG_IO_DRAIN  0x0001u
#define SQE_FLAG_IO_LINK   0x0002u
#define CQE_FLAG_CANCELED  0x0001u
#define CQE_FLAG_MORE      0x0002u

