// kernel/io/manifest_ops.c
//
// GENERATED by scripts/gen_manifest.py from /etc/gcp.json. DO NOT EDIT.
// Regenerate with `python3 scripts/gen_manifest.py` and commit the output.

#include "stream.h"
#include "../cap/pledge.h"

// Dispatcher forward declarations. Real implementations land in U8/U9 of
// Phase 18 (kernel/io/dispatch_fs.c, dispatch_ipc.c). Weak fallbacks below
// return -ENOSYS so a partial build still links.
int dispatch_read_vmo(struct stream_job *job);
int dispatch_write_vmo(struct stream_job *job);
int dispatch_sendmsg(struct stream_job *job);
int dispatch_open_stub(struct stream_job *job);
int dispatch_stat_stub(struct stream_job *job);
int dispatch_fsync_stub(struct stream_job *job);
int dispatch_close_stub(struct stream_job *job);

// Weak -ENOSYS fallbacks. U8/U9 replace these with real dispatchers.

__attribute__((weak)) int dispatch_read_vmo(struct stream_job *job) {
    (void)job;
    return -38; /* -ENOSYS */
}
__attribute__((weak)) int dispatch_write_vmo(struct stream_job *job) {
    (void)job;
    return -38; /* -ENOSYS */
}
__attribute__((weak)) int dispatch_sendmsg(struct stream_job *job) {
    (void)job;
    return -38; /* -ENOSYS */
}
__attribute__((weak)) int dispatch_open_stub(struct stream_job *job) {
    (void)job;
    return -38; /* -ENOSYS */
}
__attribute__((weak)) int dispatch_stat_stub(struct stream_job *job) {
    (void)job;
    return -38; /* -ENOSYS */
}
__attribute__((weak)) int dispatch_fsync_stub(struct stream_job *job) {
    (void)job;
    return -38; /* -ENOSYS */
}
__attribute__((weak)) int dispatch_close_stub(struct stream_job *job) {
    (void)job;
    return -38; /* -ENOSYS */
}

// Op table for manifest type "grahaos.io.v1".
static const op_schema_t op_schema_io_v1[] = {
    { .op = 1u, ._pad = 0,
      .required_pledge_mask = PLEDGE_FS_READ,
      .dispatcher = dispatch_read_vmo,
      .name = "READ_VMO" },
    { .op = 2u, ._pad = 0,
      .required_pledge_mask = PLEDGE_FS_WRITE,
      .dispatcher = dispatch_write_vmo,
      .name = "WRITE_VMO" },
    { .op = 3u, ._pad = 0,
      .required_pledge_mask = PLEDGE_IPC_SEND,
      .dispatcher = dispatch_sendmsg,
      .name = "SENDMSG" },
    { .op = 4u, ._pad = 0,
      .required_pledge_mask = PLEDGE_FS_READ,
      .dispatcher = dispatch_open_stub,
      .name = "OPEN" },
    { .op = 5u, ._pad = 0,
      .required_pledge_mask = PLEDGE_FS_READ,
      .dispatcher = dispatch_stat_stub,
      .name = "STAT" },
    { .op = 6u, ._pad = 0,
      .required_pledge_mask = PLEDGE_FS_WRITE,
      .dispatcher = dispatch_fsync_stub,
      .name = "FSYNC" },
    { .op = 7u, ._pad = 0,
      .required_pledge_mask = PLEDGE_COMPUTE,
      .dispatcher = dispatch_close_stub,
      .name = "CLOSE" },
};
static const uint16_t op_schema_io_v1_count = (uint16_t)(sizeof(op_schema_io_v1) / sizeof(op_schema_io_v1[0]));

// Registry of recognized stream manifest types. Linear scan in
// stream_lookup_manifest — the table is small (<= 8 entries).
static const manifest_entry_t g_manifest_registry[] = {
    { .type_hash = 0x731C934A2C6A037BULL,
      .ops = op_schema_io_v1,
      .op_count = op_schema_io_v1_count,
      ._pad = {0, 0, 0},
      .type_name = "grahaos.io.v1" },
    { .type_hash = 0xD4D893156B1C7693ULL,
      .ops = NULL,
      .op_count = 0,
      ._pad = {0, 0, 0},
      .type_name = "grahaos.io.completion.v1" },
    { .type_hash = 0x8CE1B2F34A88A610ULL,
      .ops = NULL,
      .op_count = 0,
      ._pad = {0, 0, 0},
      .type_name = "grahaos.notify.v1" },
    { .type_hash = 0xDDE77B853FE8322CULL,
      .ops = NULL,
      .op_count = 0,
      ._pad = {0, 0, 0},
      .type_name = "grahaos.pipe.bytes.v1" },
    { .type_hash = 0x94373FD4B7C1ED43ULL,
      .ops = NULL,
      .op_count = 0,
      ._pad = {0, 0, 0},
      .type_name = "grahaos.fault.v1" },
    { .type_hash = 0xB9BB0AACFACA5045ULL,
      .ops = NULL,
      .op_count = 0,
      ._pad = {0, 0, 0},
      .type_name = "grahaos.shutdown.v1" },
    { .type_hash = 0x0A8D84AA8BE2E342ULL,
      .ops = NULL,
      .op_count = 0,
      ._pad = {0, 0, 0},
      .type_name = "grahaos.audit.v1" },
    { .type_hash = 0xACC7E516EE71F1B3ULL,
      .ops = NULL,
      .op_count = 0,
      ._pad = {0, 0, 0},
      .type_name = "grahaos.test.v1" },
};
static const uint16_t g_manifest_registry_count = (uint16_t)(sizeof(g_manifest_registry) / sizeof(g_manifest_registry[0]));

// Public lookup. Returns NULL if hash is not registered or is listed
// but has zero ops (i.e. not a valid stream type).
const manifest_entry_t *stream_lookup_manifest(uint64_t type_hash) {
    for (uint16_t i = 0; i < g_manifest_registry_count; i++) {
        if (g_manifest_registry[i].type_hash == type_hash &&
            g_manifest_registry[i].op_count > 0) {
            return &g_manifest_registry[i];
        }
    }
    return NULL;
}

