#!/usr/bin/env python3
"""gen_manifest_blob.py — Phase 27 Stage C2 manifest blob generator.

Reads etc/gcp.json, emits kernel/manifest_blob.c containing the JSON bytes
as a `const uint8_t g_manifest_blob[]` rodata array plus its byte size and a
deterministic FNV-1a 64-bit generation hash. The kernel ships this blob via
SYS_MANIFEST_EXPORT so AI agents can read the syscall surface without
parsing a file (or being able to read /etc).

Determinism: the input is treated as raw bytes (no JSON canonicalisation).
The generated .c file embeds (a) the byte array, (b) the byte length, and
(c) the FNV-1a hash — all of which depend ONLY on the input bytes, so two
invocations on the same gcp.json produce byte-identical output. Re-run on
every gcp.json change via the Makefile dependency.

Usage:
    python3 scripts/gen_manifest_blob.py etc/gcp.json --out kernel/manifest_blob.c
"""

import argparse
import os
import sys


FNV_OFFSET = 0xCBF29CE484222325
FNV_PRIME = 0x100000001B3


def fnv1a_64(data: bytes) -> int:
    h = FNV_OFFSET
    for b in data:
        h ^= b
        h = (h * FNV_PRIME) & 0xFFFFFFFFFFFFFFFF
    return h


def emit_c(input_path: str, out_path: str) -> None:
    with open(input_path, "rb") as fh:
        blob = fh.read()
    h = fnv1a_64(blob)
    n = len(blob)

    lines = []
    lines.append("// kernel/manifest_blob.c — AUTO-GENERATED by scripts/gen_manifest_blob.py.")
    lines.append("// DO NOT EDIT BY HAND. Re-run the generator after etc/gcp.json changes.")
    lines.append("//")
    lines.append("// Phase 27 Stage C2 — provides the SYS_MANIFEST_EXPORT payload + a 64-bit")
    lines.append("// FNV-1a generation hash so AI agents can detect surface changes between")
    lines.append("// kernel builds without parsing the JSON.")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"const uint8_t g_manifest_blob[] = {{")

    # 16 bytes per line for readability.
    chunk = 16
    for i in range(0, n, chunk):
        row = blob[i : i + chunk]
        nums = ", ".join(f"0x{b:02x}" for b in row)
        lines.append(f"    {nums},")
    lines.append("};")
    lines.append("")
    lines.append(f"const uint64_t g_manifest_blob_size = {n}u;")
    lines.append(f"const uint64_t g_manifest_generation = 0x{h:016x}ull;")
    lines.append("")

    out_dir = os.path.dirname(out_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(out_path, "w") as fh:
        fh.write("\n".join(lines))

    sys.stderr.write(
        f"gen_manifest_blob: {n} bytes from {input_path} → {out_path} "
        f"(hash 0x{h:016x})\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("input", help="path to etc/gcp.json")
    ap.add_argument("--out", required=True, help="output .c file path")
    args = ap.parse_args()
    emit_c(args.input, args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
