#!/usr/bin/env python3
"""
scripts/gen_manifest.py

Phase 18 — GCP manifest generator. Reads /etc/gcp.json and emits two
artifacts:

  - kernel/io/manifest_ops.c: per-manifest op_schema_t tables and the
    manifest_registry[] lookup table. The dispatcher function pointers are
    declared as weak symbols so this file links even before U8/U9 write
    the real implementations; weak definitions return -ENOSYS so runtime
    behavior is predictable too.

  - user/include/gcp_ops_generated.h: userspace OP_* constants and
    GCP_TYPE_HASH_* macros.

Run this script manually whenever etc/gcp.json changes. The generated
files are checked in so the build does not require Python.

Usage:
    python3 scripts/gen_manifest.py
"""
from __future__ import annotations

import json
import pathlib
import sys
import textwrap


FNV64_OFFSET = 0xCBF29CE484222325
FNV64_PRIME  = 0x100000001B3
FNV64_MASK   = (1 << 64) - 1


def fnv1a_64(s: str) -> int:
    h = FNV64_OFFSET
    for b in s.encode("utf-8"):
        h ^= b
        h = (h * FNV64_PRIME) & FNV64_MASK
    return h


PLEDGE_MAP = {
    "FS_READ":     "PLEDGE_FS_READ",
    "FS_WRITE":    "PLEDGE_FS_WRITE",
    "NET_CLIENT":  "PLEDGE_NET_CLIENT",
    "NET_SERVER":  "PLEDGE_NET_SERVER",
    "SPAWN":       "PLEDGE_SPAWN",
    "IPC_SEND":    "PLEDGE_IPC_SEND",
    "IPC_RECV":    "PLEDGE_IPC_RECV",
    "SYS_QUERY":   "PLEDGE_SYS_QUERY",
    "SYS_CONTROL": "PLEDGE_SYS_CONTROL",
    "AI_CALL":     "PLEDGE_AI_CALL",
    "COMPUTE":     "PLEDGE_COMPUTE",
    "TIME":        "PLEDGE_TIME",
}


def ident_for(type_name: str) -> str:
    """grahaos.io.v1  ->  io_v1"""
    stem = type_name.removeprefix("grahaos.").replace(".", "_")
    return stem


def emit_kernel(manifest: dict, out_path: pathlib.Path) -> None:
    types_with_ops = {
        name: body for name, body in manifest["types"].items()
        if body.get("ops")
    }

    lines: list[str] = []
    add = lines.append

    add("// kernel/io/manifest_ops.c")
    add("//")
    add("// GENERATED by scripts/gen_manifest.py from /etc/gcp.json. DO NOT EDIT.")
    add("// Regenerate with `python3 scripts/gen_manifest.py` and commit the output.")
    add("")
    add('#include "stream.h"')
    add('#include "../cap/pledge.h"')
    add("")
    add("// Dispatcher forward declarations. Real implementations land in U8/U9 of")
    add("// Phase 18 (kernel/io/dispatch_fs.c, dispatch_ipc.c). Weak fallbacks below")
    add("// return -ENOSYS so a partial build still links.")

    # Collect unique dispatcher names
    dispatcher_set: list[str] = []
    for name, body in types_with_ops.items():
        for op_name, op_body in body["ops"].items():
            dname = op_body["dispatcher"]
            if dname not in dispatcher_set:
                dispatcher_set.append(dname)

    for dname in dispatcher_set:
        add(f"int {dname}(struct stream_job *job);")
    add("")

    # Weak fallback stubs — each returns -ENOSYS=-38 on invocation. Until U4
    # lands stream_complete_job, these stubs must not reference it — the real
    # dispatchers in U8/U9 override these and always call stream_complete_job
    # before returning.
    add("// Weak -ENOSYS fallbacks. U8/U9 replace these with real dispatchers.")
    add("")
    for dname in dispatcher_set:
        add(f"__attribute__((weak)) int {dname}(struct stream_job *job) {{")
        add("    (void)job;")
        add("    return -38; /* -ENOSYS */")
        add("}")
    add("")

    # Per-type op_schema tables.
    for name, body in types_with_ops.items():
        ident = ident_for(name)
        ops = body["ops"]
        # Sort by op number for deterministic layout.
        sorted_ops = sorted(ops.items(), key=lambda kv: kv[1]["op"])
        add(f"// Op table for manifest type \"{name}\".")
        add(f"static const op_schema_t op_schema_{ident}[] = {{")
        for op_name, op_body in sorted_ops:
            pledge = PLEDGE_MAP[op_body["pledge"]]
            dname  = op_body["dispatcher"]
            opnum  = op_body["op"]
            add(f"    {{ .op = {opnum}u, ._pad = 0,")
            add(f"      .required_pledge_mask = {pledge},")
            add(f"      .dispatcher = {dname},")
            add(f"      .name = \"{op_name}\" }},")
        add("};")
        add(f"static const uint16_t op_schema_{ident}_count = "
            f"(uint16_t)(sizeof(op_schema_{ident}) / sizeof(op_schema_{ident}[0]));")
        add("")

    # manifest_registry.
    add("// Registry of recognized stream manifest types. Linear scan in")
    add("// stream_lookup_manifest — the table is small (<= 8 entries).")
    add("static const manifest_entry_t g_manifest_registry[] = {")
    for name, body in manifest["types"].items():
        ident = ident_for(name)
        type_hash = fnv1a_64(name)
        if body.get("ops"):
            ops_ref = f"op_schema_{ident}"
            count_ref = f"op_schema_{ident}_count"
        else:
            # Type exists but has no stream ops (it's a channel msg type). The
            # registry still lists it so validation errors are prettier, but
            # the stream subsystem rejects a stream_create pointing at it
            # because op_count == 0.
            ops_ref = "NULL"
            count_ref = "0"
        add(f"    {{ .type_hash = 0x{type_hash:016X}ULL,")
        add(f"      .ops = {ops_ref},")
        add(f"      .op_count = {count_ref},")
        add(f"      ._pad = {{0, 0, 0}},")
        add(f"      .type_name = \"{name}\" }},")
    add("};")
    add("static const uint16_t g_manifest_registry_count = "
        "(uint16_t)(sizeof(g_manifest_registry) / "
        "sizeof(g_manifest_registry[0]));")
    add("")
    add("// Public lookup. Returns NULL if hash is not registered or is listed")
    add("// but has zero ops (i.e. not a valid stream type).")
    add("const manifest_entry_t *stream_lookup_manifest(uint64_t type_hash) {")
    add("    for (uint16_t i = 0; i < g_manifest_registry_count; i++) {")
    add("        if (g_manifest_registry[i].type_hash == type_hash &&")
    add("            g_manifest_registry[i].op_count > 0) {")
    add("            return &g_manifest_registry[i];")
    add("        }")
    add("    }")
    add("    return NULL;")
    add("}")
    add("")

    out_path.write_text("\n".join(lines) + "\n")


def emit_userspace(manifest: dict, out_path: pathlib.Path) -> None:
    lines: list[str] = []
    add = lines.append

    add("// user/include/gcp_ops_generated.h")
    add("//")
    add("// GENERATED by scripts/gen_manifest.py from /etc/gcp.json. DO NOT EDIT.")
    add("// Userspace OP_* constants and GCP_TYPE_HASH_* macros for Phase 18.")
    add("")
    add("#pragma once")
    add("#include <stdint.h>")
    add("")

    # OP_ constants. Collect by walking all ops in all types.
    add("// Opcodes. Values must match kernel/io/stream.h (enforced at runtime")
    add("// when the shared sqe_t is validated against the kernel op_schema).")
    # Use a dict to avoid dups if same op name appears twice (shouldn't).
    seen_ops: dict[str, int] = {}
    for name, body in manifest["types"].items():
        for op_name, op_body in body.get("ops", {}).items():
            key = op_name
            if key in seen_ops and seen_ops[key] != op_body["op"]:
                raise SystemExit(
                    f"op name {key} has conflicting numbers: "
                    f"{seen_ops[key]} vs {op_body['op']}"
                )
            seen_ops[key] = op_body["op"]
    for op_name in sorted(seen_ops, key=lambda k: seen_ops[k]):
        add(f"#define OP_{op_name:<10s} {seen_ops[op_name]}u")
    add("")
    add("// Type-hash macros. FNV-1a 64-bit of the manifest type string.")
    for name in manifest["types"]:
        sym = "GCP_TYPE_HASH_" + ident_for(name).upper()
        add(f"#define {sym:<40s} 0x{fnv1a_64(name):016X}ULL")
    add("")

    # SQE/CQE flag constants mirror stream.h.
    add("// SQE/CQE flag mirrors — values match kernel/io/stream.h.")
    add("#define SQE_FLAG_IO_DRAIN  0x0001u")
    add("#define SQE_FLAG_IO_LINK   0x0002u")
    add("#define CQE_FLAG_CANCELED  0x0001u")
    add("#define CQE_FLAG_MORE      0x0002u")
    add("")

    out_path.write_text("\n".join(lines) + "\n")


def main() -> int:
    repo = pathlib.Path(__file__).resolve().parent.parent
    gcp_path = repo / "etc" / "gcp.json"
    kern_out = repo / "kernel" / "io" / "manifest_ops.c"
    user_out = repo / "user" / "include" / "gcp_ops_generated.h"
    user_out.parent.mkdir(parents=True, exist_ok=True)

    manifest = json.loads(gcp_path.read_text())
    emit_kernel(manifest, kern_out)
    emit_userspace(manifest, user_out)

    # Sanity: echo computed hashes so it's obvious when they change.
    print("Type hashes (FNV-1a 64):")
    for name in manifest["types"]:
        print(f"  {name:40s} = 0x{fnv1a_64(name):016X}")
    print(f"\nWrote {kern_out.relative_to(repo)}")
    print(f"Wrote {user_out.relative_to(repo)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
